/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    './pages/**/*.{js,ts,jsx,tsx,mdx}',
    './components/**/*.{js,ts,jsx,tsx,mdx}',
    './app/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  theme: {
    extend: {
      fontFamily: {
        sans: ['var(--font-sans)'],
        serif: ['var(--font-serif)'],
      },
      colors: {
        /* Nepali-inspired colors */
        saffron: 'var(--saffron)',
        'deep-saffron': 'var(--deep-saffron)',
        crimson: 'var(--crimson)',
        maroon: 'var(--maroon)',
        gold: 'var(--gold)',
        'warm-gold': 'var(--warm-gold)',
        'himalayan-blue': 'var(--himalayan-blue)',
        'earth-brown': 'var(--earth-brown)',
        'forest-green': 'var(--forest-green)',
        'warm-cream': 'var(--warm-cream)',
        'soft-beige': 'var(--soft-beige)',
        /* Legacy colors for compatibility */
        rosewater: 'var(--rosewater)',
        flamingo: 'var(--flamingo)',
        pink: 'var(--pink)',
        mauve: 'var(--mauve)',
        red: 'var(--red)',
        peach: 'var(--peach)',
        yellow: 'var(--yellow)',
        green: 'var(--green)',
        teal: 'var(--teal)',
        sky: 'var(--sky)',
        sapphire: 'var(--sapphire)',
        blue: 'var(--blue)',
        orange: 'var(--orange)',
        'warm-orange': 'var(--warm-orange)',
        'light-blue': 'var(--light-blue)',
        lavender: 'var(--lavender)',
        text: 'var(--text)',
        subtext1: 'var(--subtext1)',
        subtext0: 'var(--subtext0)',
        overlay2: 'var(--overlay2)',
        overlay1: 'var(--overlay1)',
        overlay0: 'var(--overlay0)',
        surface2: 'var(--surface2)',
        surface1: 'var(--surface1)',
        surface0: 'var(--surface0)',
        base: 'rgb(var(--base) / <alpha-value>)',
        mantle: 'var(--mantle)',
        crust: 'var(--crust)',
      },
      backgroundImage: {
        'gradient-radial': 'radial-gradient(var(--tw-gradient-stops))',
        'gradient-conic':
          'conic-gradient(from 180deg at 50% 50%, var(--tw-gradient-stops))',
      },
    },
  },
  plugins: [],
}
